### ISSUE TITLE
issue while deploying/installing

### ISSUE THREAD

**Issue by Hari-GIT1** [verma-kunal/AWS-Session#9]
ubuntu@ip-172-31-12-54:~/AWS-Session$ npm run start

> stripe-integration@1.0.0 start /home/ubuntu/AWS-Session
> node server.js

/home/ubuntu/AWS-Session/server.js:3
const { resolve } = require("path");
      ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
npm ERR! weird error 8
npm ERR! not ok code 0

**Comment by arashutosh** [comment]
there is an error on line numbe 3 in server.js
give more brief about the issue

**Comment by BeinGHuan** [comment]
> ubuntu@ip-172-31-12-54:~/AWS-Session$ npm run start
> 
> > stripe-integration@1.0.0 start /home/ubuntu/AWS-Session
> > node server.js
> 
> /home/ubuntu/AWS-Session/server.js:3 const { resolve } = require("path"); ^ SyntaxError: Unexpected token { at Module._compile (module.js:439:25) at Object.Module._extensions..js (module.js:474:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) at Function.Module.runMain (module.js:497:10) at startup (node.js:119:16) at node.js:901:3 npm ERR! weird error 8 npm ERR! not ok code 0

It is probably because of the update issue of the module files when we try to install using node package manager.
I too tried to install and got 3 vulnerabilites and when i tried to audit and fix it that didnt work either.



PS C:\mrdevops\AWS_project\aws-session> npm audit ffix
# npm audit report

semver  7.0.0 - 7.5.1
Severity: high
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix`
node_modules/simple-update-notifier/node_modules/semver
  simple-update-notifier  1.0.7 - 1.1.0
  Depends on vulnerable versions of semver
  node_modules/simple-update-notifier
    nodemon  2.0.19 - 2.0.22
    Depends on vulnerable versions of simple-update-notifier
    node_modules/nodemon

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix

up to date, audited 99 packages in 2s

17 packages are looking for funding
  run `npm fund` for details

# npm audit report

semver  7.0.0 - 7.5.1
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix`
node_modules/simple-update-notifier/node_modules/semver
  simple-update-notifier  1.0.7 - 1.1.0
  Depends on vulnerable versions of semver
  node_modules/simple-update-notifier
    nodemon  2.0.19 - 2.0.22
    Depends on vulnerable versions of simple-update-notifier

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix
PS C:\mrdevops\AWS_project\aws-session> nodemon simple-update-modifier
nodemon : The term 'nodemon' is not recognized as the name of a cmdlet, function, script file, or   
operable program. Check the spelling of the name, or if a path was included, verify that the path   
is correct and try again.
At line:1 char:1
+ nodemon simple-update-modifier
+ ~~~~~~~
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\mrdevops\AWS_project\aws-session> nodemon simple-update-modifier 1.0.7
nodemon : The term 'nodemon' is not recognized as the name of a cmdlet, function, script file, or   
operable program. Check the spelling of the name, or if a path was included, verify that the path   
is correct and try again.
At line:1 char:1
+ nodemon simple-update-modifier 1.0.7
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (nodemon:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PS C:\mrdevops\AWS_project\aws-session> npm update

up to date, audited 99 packages in 3s

17 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix

  npm audit fix


Run `npm audit` for details.
PS C:\mrdevops\AWS_project\aws-session> npm run start


> stripe-integration@1.0.0 start
> node server.js
> node server.js


node:internal/errors:541
      throw error;
      ^

    at resolve (node:path:195:9)
    at Object.<anonymous> (C:\mrdevops\AWS_project\aws-session\server.js:17:24)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.17.0

up to date, audited 99 packages in 1s

17 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
PS C:\mrdevops\AWS_project\aws-session> npm audit fix

up to date, audited 99 packages in 2s

17 packages are looking for funding
  run `npm fund` for details

# npm audit report

semver  7.0.0 - 7.5.1
Severity: high
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
node_modules/simple-update-notifier/node_modules/semver
  simple-update-notifier  1.0.7 - 1.1.0
  Depends on vulnerable versions of semver
  node_modules/simple-update-notifier
    nodemon  2.0.19 - 2.0.22
    Depends on vulnerable versions of simple-update-notifier
    node_modules/nodemon

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix
PS C:\mrdevops\AWS_project\aws-session> npm run start

> stripe-integration@1.0.0 start
> node server.js

node:internal/errors:541
      throw error;
      ^

    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.17.0
PS C:\mrdevops\AWS_project\aws-session>




                                        npm audit
# npm audit report

semver  7.0.0 - 7.5.1
Severity: high
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
node_modules/simple-update-notifier/node_modules/semver
  simple-update-notifier  1.0.7 - 1.1.0
  Depends on vulnerable versions of semver
  node_modules/simple-update-notifier
    nodemon  2.0.19 - 2.0.22
    Depends on vulnerable versions of simple-update-notifier
    node_modules/nodemon

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix
PS C:\mrdevops\AWS_project\aws-session> npm audit fix

up to date, audited 99 packages in 2s

17 packages are looking for funding
  run `npm fund` for details

# npm audit report

semver  7.0.0 - 7.5.1
Severity: high
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
node_modules/simple-update-notifier/node_modules/semver
  simple-update-notifier  1.0.7 - 1.1.0
  Depends on vulnerable versions of semver
  node_modules/simple-update-notifier
    nodemon  2.0.19 - 2.0.22
    Depends on vulnerable versions of simple-update-notifier
    node_modules/nodemon

3 high severity vulnerabilities

To address all issues, run:
  npm audit fix
PS C:\mrdevops\AWS_project\aws-session> npm run start

> stripe-integration@1.0.0 start
> node server.js

node:internal/errors:541
      throw error;
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined    at resolve (node:path:195:9)
    at Object.<anonymous> (C:\mrdevops\AWS_project\aws-session\server.js:17:24)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Does anyone know how to fix this manually
 It's been two days since I have been stuck at this.


Node.js v20.17.0
PS C:\mrdevops\AWS_project\aws-session>

**Comment by BeinGHuan** [comment]
> ubuntu@ip-172-31-12-54:~/AWS-Session$ npm run start
> 
> > stripe-integration@1.0.0 start /home/ubuntu/AWS-Session
> > node server.js
> 
> /home/ubuntu/AWS-Session/server.js:3 const { resolve } = require("path"); ^ SyntaxError: Unexpected token { at Module._compile (module.js:439:25) at Object.Module._extensions..js (module.js:474:10) at Module.load (module.js:356:32) at Function.Module._load (module.js:312:12) at Function.Module.runMain (module.js:497:10) at startup (node.js:119:16) at node.js:901:3 npm ERR! weird error 8 npm ERR! not ok code 0

This is probably because of the update of the node package manager as there may be vulnerabilities that the device is not able to rectify.

Try 
>npm audit
>npm audit fix
>npm update 
>npm run start

Even if there's an error try installing the packages manually.
Even if that doesn't work either then contact expert professional for the error that you are getting.

**Comment by BeinGHuan** [comment]
> there is an error on line numbe 3 in server.js give more brief about the issue

You can try the same method mentioned above as well and check if that works.

**Comment by HariHaran0091** [comment]
use stripe keys
